//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 自增ID与其它混合测试模型业务数据服务接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(IAutoIdentityModelServiceMethodEnum))]
        public partial interface IAutoIdentityModelService { }
}namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 自定义字段列测试模型业务数据服务接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ICustomColumnFieldModelServiceMethodEnum))]
        public partial interface ICustomColumnFieldModelService { }
}namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 自定义属性列测试模型业务数据服务接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ICustomColumnPropertyModelServiceMethodEnum))]
        public partial interface ICustomColumnPropertyModelService { }
}namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 字段测试模型业务数据服务接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(IFieldModelServiceMethodEnum))]
        public partial interface IFieldModelService { }
}namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 属性测试模型业务数据服务接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(IPropertyModelServiceMethodEnum))]
        public partial interface IPropertyModelService { }
}
#endif