//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.Document.SymmetryService
{
        /// <summary>
        /// Interface symmetry API interface definition (Interface Symmetric apis do not need to generate client interfaces so set IsCodeGeneratorClientInterface to false) 
///            接口对称 API 接口定义（接口对称 API 不需要生成客户端接口所以设置 IsCodeGeneratorClientInterface 为 false）
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ISymmetryServiceMethodEnum))]
        public partial interface ISymmetryService { }
        /// <summary>
        /// Interface symmetry API interface definition (Interface Symmetric apis do not need to generate client interfaces so set IsCodeGeneratorClientInterface to false) 
///            接口对称 API 接口定义（接口对称 API 不需要生成客户端接口所以设置 IsCodeGeneratorClientInterface 为 false） (The method sequence number maps the enumeration type)
        /// </summary>
        public enum ISymmetryServiceMethodEnum
        {
            /// <summary>
            /// [0] Synchronous API definition (It is not recommended to define the synchronous API in interface symmetric services, as the client synchronous blocking mode may cause performance bottlenecks) 
///            同步 API 定义（不建议在接口对称服务中定义同步 API，因为客户端同步阻塞模式可能造成性能瓶颈）
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Add = 0,
            /// <summary>
            /// [1] Asynchronous API definition 
///            异步 API 定义
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            AddAsync = 1,
        }
}
#endif