//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.TestCase.Common
{
    public partial class JsonFileConfig
    {
            /// <summary>
            /// JSON deserialization
            /// JSON 反序列化
            /// </summary>
            /// <param name="deserializer"></param>
            /// <param name="value"></param>
            /// <param name="names"></param>
            internal static void JsonDeserialize(AutoCSer.JsonDeserializer deserializer, ref AutoCSer.TestCase.Common.JsonFileConfig value, ref AutoCSer.Memory.Pointer names)
            {
                value.jsonDeserialize(deserializer, ref names);
            }
            /// <summary>
            /// JSON deserialization of member bitmaps is supported
            /// 支持成员位图的 JSON 反序列化
            /// </summary>
            /// <param name="deserializer"></param>
            /// <param name="value"></param>
            /// <param name="names"></param>
            /// <param name="memberMap"></param>
            internal static void JsonDeserializeMemberMap(AutoCSer.JsonDeserializer deserializer, ref AutoCSer.TestCase.Common.JsonFileConfig value, ref AutoCSer.Memory.Pointer names, AutoCSer.Metadata.MemberMap<AutoCSer.TestCase.Common.JsonFileConfig> memberMap)
            {
                value.jsonDeserialize(deserializer, ref names, memberMap);
            }
            /// <summary>
            /// JSON deserialization
            /// JSON 反序列化
            /// </summary>
            /// <param name="__deserializer__"></param>
            /// <param name="__names__"></param>
            private void jsonDeserialize(AutoCSer.JsonDeserializer __deserializer__, ref AutoCSer.Memory.Pointer __names__)
            {
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.HttpsCertificateFileName);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.HttpsCertificatePassword);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.IsLinuxServer);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.IsRemote);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.ServerHost);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.TimestampVerifyString);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.UploadPath);
                    if (!AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) return;
                }
                else return;
            }
            /// <summary>
            /// JSON deserialization of member bitmaps is supported
            /// 支持成员位图的 JSON 反序列化
            /// </summary>
            /// <param name="__deserializer__"></param>
            /// <param name="__names__"></param>
            /// <param name="__memberMap__"></param>
            private void jsonDeserialize(AutoCSer.JsonDeserializer __deserializer__, ref AutoCSer.Memory.Pointer __names__, AutoCSer.Metadata.MemberMap<AutoCSer.TestCase.Common.JsonFileConfig> __memberMap__)
            {
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.HttpsCertificateFileName);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(0);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.HttpsCertificatePassword);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(1);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.IsLinuxServer);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(2);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.IsRemote);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(3);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.ServerHost);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(4);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.TimestampVerifyString);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(5);
                    else return;
                }
                else return;
                if (__deserializer__.IsName(ref __names__))
                {
                    __deserializer__.JsonDeserialize(ref this.UploadPath);
                    if (AutoCSer.JsonDeserializer.NextNameIndex(__deserializer__, ref __names__)) __memberMap__.SetMember(6);
                    else return;
                }
                else return;
            }
            /// <summary>
            /// Member JSON deserialization
            /// 成员 JSON 反序列化
            /// </summary>
            /// <param name="__deserializer__"></param>
            /// <param name="__value__"></param>
            /// <param name="__memberIndex__"></param>
            internal static void JsonDeserialize(AutoCSer.JsonDeserializer __deserializer__, ref AutoCSer.TestCase.Common.JsonFileConfig __value__, int __memberIndex__)
            {
                switch (__memberIndex__)
                {
                    case 0:
                        __deserializer__.JsonDeserialize(ref __value__.HttpsCertificateFileName);
                        return;
                    case 1:
                        __deserializer__.JsonDeserialize(ref __value__.HttpsCertificatePassword);
                        return;
                    case 2:
                        __deserializer__.JsonDeserialize(ref __value__.IsLinuxServer);
                        return;
                    case 3:
                        __deserializer__.JsonDeserialize(ref __value__.IsRemote);
                        return;
                    case 4:
                        __deserializer__.JsonDeserialize(ref __value__.ServerHost);
                        return;
                    case 5:
                        __deserializer__.JsonDeserialize(ref __value__.TimestampVerifyString);
                        return;
                    case 6:
                        __deserializer__.JsonDeserialize(ref __value__.UploadPath);
                        return;
                }
            }
            /// <summary>
            /// Gets the JSON deserialization member name collection and member index collection
            /// 获取 JSON 反序列化成员名称集合与成员索引集合
            /// </summary>
            /// <returns></returns>
            internal static AutoCSer.KeyValue<AutoCSer.LeftArray<string>, AutoCSer.LeftArray<int>> JsonDeserializeMemberNames()
            {
                return jsonDeserializeMemberName();
            }
            /// <summary>
            /// Gets the JSON deserialization member name collection and member index collection
            /// 获取 JSON 反序列化成员名称集合与成员索引集合
            /// </summary>
            /// <returns></returns>
            private static AutoCSer.KeyValue<AutoCSer.LeftArray<string>, AutoCSer.LeftArray<int>> jsonDeserializeMemberName()
            {
                AutoCSer.LeftArray<string> names = new AutoCSer.LeftArray<string>(7);
                AutoCSer.LeftArray<int> indexs = new AutoCSer.LeftArray<int>(7);
                names.Add(nameof(HttpsCertificateFileName));
                indexs.Add(0);
                names.Add(nameof(HttpsCertificatePassword));
                indexs.Add(1);
                names.Add(nameof(IsLinuxServer));
                indexs.Add(2);
                names.Add(nameof(IsRemote));
                indexs.Add(3);
                names.Add(nameof(ServerHost));
                indexs.Add(4);
                names.Add(nameof(TimestampVerifyString));
                indexs.Add(5);
                names.Add(nameof(UploadPath));
                indexs.Add(6);
                return new AutoCSer.KeyValue<AutoCSer.LeftArray<string>, AutoCSer.LeftArray<int>>(names, indexs);
            }
            /// <summary>
            /// AOT code generation call activation reflection
            /// AOT 代码生成调用激活反射
            /// </summary>
            internal static void JsonSerialize()
            {
                AutoCSer.TestCase.Common.JsonFileConfig value = default(AutoCSer.TestCase.Common.JsonFileConfig);
                AutoCSer.Memory.Pointer names = default(AutoCSer.Memory.Pointer);
                JsonDeserialize(null, ref value, ref names);
                JsonDeserializeMemberMap(null, ref value, ref names, null);
                JsonDeserialize(null, ref value, 0);
                JsonDeserializeMemberNames();
                AutoCSer.AotReflection.ConstructorNonPublicMethods(typeof(AutoCSer.TestCase.Common.JsonFileConfig));
                AutoCSer.AotReflection.NonPublicMethods(typeof(AutoCSer.TestCase.Common.JsonFileConfig));
            }
    }
}namespace AutoCSer.TestCase.Common
{
    public partial class JsonFileConfig
    {
            /// <summary>
            /// Call the default constructor
            /// 调用默认构造函数
            /// </summary>
            internal static AutoCSer.TestCase.Common.JsonFileConfig DefaultConstructor()
            {
                return new AutoCSer.TestCase.Common.JsonFileConfig();
            }
            /// <summary>
            /// AOT code generation call activation reflection
            /// AOT 代码生成调用激活反射
            /// </summary>
            internal static void DefaultConstructorReflection()
            {
                DefaultConstructor();
                AutoCSer.Metadata.DefaultConstructor.GetIsSerializeConstructor<AutoCSer.TestCase.Common.JsonFileConfig>();
            }
    }
}namespace AutoCSer.TestCase.Common
{
    /// <summary>
    /// 触发 AOT 编译
    /// </summary>
    public static class AotMethod
    {
            /// <summary>
            /// AOT code generation call activation reflection
            /// AOT 代码生成调用激活反射
            /// </summary>
            /// <returns></returns>
            public static bool Call()
            {
                if (AutoCSer.Date.StartTimestamp == long.MinValue)
                {
                    AutoCSer.TestCase.Common.JsonFileConfig/**/.JsonSerialize();
                    AutoCSer.TestCase.Common.JsonFileConfig/**/.DefaultConstructorReflection();


                    AutoCSer.AotReflection.NonPublicFields(typeof(AutoCSer.Json.TypeSerializer<string>));
                    AutoCSer.AotReflection.NonPublicFields(typeof(AutoCSer.Json.TypeSerializer<bool>));


                    return true;
                }
                return false;
            }
    }
}
#endif