//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.Document.ServiceAuthentication.CustomVerify
{
        /// <summary>
        /// A service authentication interface for customizing user identity authentication 
///            自定义用户身份鉴权服务认证接口 client interface
        /// </summary>
        public partial interface ICustomVerifyServiceClientController
        {
            /// <summary>
            /// Verification method 
///            验证方法
            /// </summary>
            /// <param name="verifyData">Customize user identity authentication data 
///            自定义用户身份鉴权数据</param>
            /// <param name="hashData">Hash data to be verified 
///            待验证 Hash 数据</param>
            /// <returns></returns>
            AutoCSer.Net.ReturnCommand<AutoCSer.Net.CommandServerVerifyStateEnum> Verify(AutoCSer.Document.ServiceAuthentication.CustomVerify.CustomVerifyData verifyData, byte[] hashData);
        }
}namespace AutoCSer.Document.ServiceAuthentication
{
        /// <summary>
        /// Test the service interface definition (Generate the client interface code) 
///            测试服务接口定义（生成客户端接口代码） client interface
        /// </summary>
        public partial interface ITestServiceClientController
        {
            /// <summary>
            /// Test the service API definition 
///            测试服务 API 定义
            /// </summary>
            /// <param name="left"></param>
            /// <param name="right"></param>
            /// <returns></returns>
            AutoCSer.Net.ReturnCommand<int> Add(int left, int right);
            /// <summary>
            /// Api that are not allowed to be accessed (for the specified API testing of the user identity-based authentication mode) 
///            不允许访问的 API（用于基于用户身份的鉴权模式的指定 API 测试）
            /// </summary>
            AutoCSer.Net.ReturnCommand NotSetCommand();
        }
}namespace AutoCSer.Document.ServiceAuthentication.CustomVerify
{
        /// <summary>
        /// A service authentication interface for customizing user identity authentication 
///            自定义用户身份鉴权服务认证接口
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ICustomVerifyServiceMethodEnum))]
        public partial interface ICustomVerifyService { }
        /// <summary>
        /// A service authentication interface for customizing user identity authentication 
///            自定义用户身份鉴权服务认证接口 (The method sequence number maps the enumeration type)
        /// </summary>
        public enum ICustomVerifyServiceMethodEnum
        {
            /// <summary>
            /// [0] Verification method 
///            验证方法
            /// AutoCSer.Net.CommandServerSocket socket 
            /// AutoCSer.Document.ServiceAuthentication.CustomVerify.CustomVerifyData verifyData Customize user identity authentication data 
///            自定义用户身份鉴权数据
            /// byte[] hashData Hash data to be verified 
///            待验证 Hash 数据
            /// 返回值 AutoCSer.Net.CommandServerVerifyStateEnum 
            /// </summary>
            Verify = 0,
        }
}namespace AutoCSer.Document.ServiceAuthentication
{
        /// <summary>
        /// Test the service interface definition (Generate the client interface code) 
///            测试服务接口定义（生成客户端接口代码）
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ITestServiceMethodEnum))]
        public partial interface ITestService { }
        /// <summary>
        /// Test the service interface definition (Generate the client interface code) 
///            测试服务接口定义（生成客户端接口代码） (The method sequence number maps the enumeration type)
        /// </summary>
        public enum ITestServiceMethodEnum
        {
            /// <summary>
            /// [0] Test the service API definition 
///            测试服务 API 定义
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Add = 0,
            /// <summary>
            /// [1] Api that are not allowed to be accessed (for the specified API testing of the user identity-based authentication mode) 
///            不允许访问的 API（用于基于用户身份的鉴权模式的指定 API 测试）
            /// </summary>
            NotSetCommand = 1,
        }
}
#endif