//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.TestCase.CommandServerPerformance
{
        /// <summary>
        /// 
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(IServiceMethodEnum))]
        public partial interface IService { }
        /// <summary>
        ///  (The method sequence number maps the enumeration type)
        /// </summary>
        public enum IServiceMethodEnum
        {
            /// <summary>
            /// [0] 
            /// int left 
            /// int right 
            /// AutoCSer.Net.CommandServerCallback{int} callback 
            /// 返回值 int 
            /// </summary>
            Callback = 0,
            /// <summary>
            /// [1] 
            /// AutoCSer.Net.CommandServerCallConcurrencyReadQueue queue 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            ConcurrencyReadQueue = 1,
            /// <summary>
            /// [2] 
            /// AutoCSer.Net.CommandServerKeepCallback{int} callback 
            /// 返回值 int 
            /// </summary>
            KeepCallback = 2,
            /// <summary>
            /// [3] 
            /// AutoCSer.Net.CommandServerKeepCallbackCount{int} callback 
            /// 返回值 int 
            /// </summary>
            KeepCallbackCount = 3,
            /// <summary>
            /// [4] 
            /// AutoCSer.Net.CommandServerCallQueue queue 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Queue = 4,
            /// <summary>
            /// [5] 
            /// AutoCSer.Net.CommandServerCallReadQueue queue 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            ReadWriteQueue = 5,
            /// <summary>
            /// [6] 
            /// int left 
            /// int right 
            /// </summary>
            SendOnly = 6,
            /// <summary>
            /// [7] 
            /// int left 
            /// int right 
            /// </summary>
            SendOnlyTask = 7,
            /// <summary>
            /// [8] 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Synchronous = 8,
            /// <summary>
            /// [9] 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            SynchronousCallTask = 9,
            /// <summary>
            /// [10] 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Task = 10,
            /// <summary>
            /// [11] 
            /// AutoCSer.Net.CommandServerCallTaskQueue queue 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            TaskQueue = 11,
            /// <summary>
            /// [12] 
            /// AutoCSer.Net.CommandServerCallTaskQueue{int} queue 
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            TaskQueueKey = 12,
        }
}
#endif