//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.CommandService
{
        /// <summary>
        /// Reverse service authentication interface based on incremental login timestamp verification (combined with HASH to prevent replay login operations) 
///            基于递增登录时间戳验证的反向服务认证接口（配合 HASH 防止重放登录操作） client interface
        /// </summary>
        public partial interface ITimestampVerifyReverseServiceClientController<T>
        {
            /// <summary>
            /// Get the reverse service verification data 
///            获取反向服务验证数据
            /// </summary>
            /// <param name="timestamp">Timestamp to be verified 
///            待验证时间戳</param>
            /// <returns>Reverse service verification data 
///            反向服务验证数据</returns>
            AutoCSer.Net.ReturnCommand<AutoCSer.CommandService.TimestampVerify.ReverseServiceVerifyData<T>> GetVerifyData(long timestamp);
        }
}namespace AutoCSer.CommandService
{
        /// <summary>
        /// Reverse service authentication interface based on incremental login timestamp verification (combined with HASH to prevent replay login operations) 
///            基于递增登录时间戳验证的反向服务认证接口（配合 HASH 防止重放登录操作）
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(ITimestampVerifyReverseServiceMethodEnum))]
        public partial interface ITimestampVerifyReverseService<T> { }
        /// <summary>
        /// Reverse service authentication interface based on incremental login timestamp verification (combined with HASH to prevent replay login operations) 
///            基于递增登录时间戳验证的反向服务认证接口（配合 HASH 防止重放登录操作） (The method sequence number maps the enumeration type)
        /// </summary>
        public enum ITimestampVerifyReverseServiceMethodEnum
        {
            /// <summary>
            /// [0] Get the reverse service verification data 
///            获取反向服务验证数据
            /// AutoCSer.Net.CommandServerSocket socket 
            /// long timestamp Timestamp to be verified 
///            待验证时间戳
            /// 返回值 AutoCSer.CommandService.TimestampVerify.ReverseServiceVerifyData{T} Reverse service verification data 
///            反向服务验证数据
            /// </summary>
            GetVerifyData = 0,
        }
}
#endif