//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 自增ID与其它混合测试模型业务数据服务接口 (The method sequence number maps the enumeration type)
        /// </summary>
        public enum IAutoIdentityModelServiceMethodEnum
        {
            /// <summary>
            /// [0] 自定义列查询测试
            /// 返回值 int 查询数据数量
            /// </summary>
            CustomColumnQuery = 0,
            /// <summary>
            /// [1] 
            /// AutoCSer.TestCase.BusinessService.AutoIdentityModel value 
            /// 返回值 long 
            /// </summary>
            Insert = 1,
            /// <summary>
            /// [2] 
            /// AutoCSer.TestCase.BusinessService.AutoIdentityModel value 
            /// 返回值 bool 
            /// </summary>
            Delete = 2,
            /// <summary>
            /// [3] 
            /// long key 
            /// 返回值 bool 
            /// </summary>
            DeleteKey = 3,
            /// <summary>
            /// [4] 
            /// long key 
            /// 返回值 AutoCSer.TestCase.BusinessService.AutoIdentityModel 
            /// </summary>
            Get = 4,
            /// <summary>
            /// [5] 
            /// AutoCSer.Metadata.MemberMapValue{AutoCSer.TestCase.CommonModel.TableModel.AutoIdentityModel,AutoCSer.TestCase.BusinessService.AutoIdentityModel} value 
            /// 返回值 bool 
            /// </summary>
            Update = 5,
        }
}
#endif