//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.TestCase.BusinessService
{
        /// <summary>
        /// 自定义属性列测试模型业务数据服务接口 (The method sequence number maps the enumeration type)
        /// </summary>
        public enum ICustomColumnPropertyModelServiceMethodEnum
        {
            /// <summary>
            /// [0] 
            /// AutoCSer.TestCase.BusinessService.CustomColumnPropertyModel value 
            /// 返回值 bool 
            /// </summary>
            Delete = 0,
            /// <summary>
            /// [1] 
            /// AutoCSer.TestCase.CommonModel.TableModel.CustomColumn.CustomColumnPropertyPrimaryKey key 
            /// 返回值 bool 
            /// </summary>
            DeleteKey = 1,
            /// <summary>
            /// [2] 
            /// AutoCSer.TestCase.CommonModel.TableModel.CustomColumn.CustomColumnPropertyPrimaryKey key 
            /// 返回值 AutoCSer.TestCase.BusinessService.CustomColumnPropertyModel 
            /// </summary>
            Get = 2,
            /// <summary>
            /// [3] 
            /// AutoCSer.Metadata.MemberMapValue{AutoCSer.TestCase.CommonModel.TableModel.CustomColumnPropertyModel,AutoCSer.TestCase.BusinessService.CustomColumnPropertyModel} value 
            /// 返回值 bool 
            /// </summary>
            Update = 3,
            /// <summary>
            /// [4] 自定义列查询测试
            /// 返回值 int 查询数据数量
            /// </summary>
            CustomColumnQuery = 4,
            /// <summary>
            /// [5] 
            /// AutoCSer.TestCase.BusinessService.CustomColumnPropertyModel value 
            /// 返回值 bool 
            /// </summary>
            Insert = 5,
        }
}
#endif