//This file is automatically generated by a program. Please do not modify it by yourself.
//本文件由程序自动生成，请不要自行修改
using System;
using System.Numerics;
using AutoCSer;

#if NoAutoCSer
#else
#pragma warning disable
namespace AutoCSer.Document.NativeAOT.Service
{
        /// <summary>
        /// An example of generate the API definition of the client controller interface 
///            生成客户端控制器接口 API 定义示例 client interface
        /// </summary>
        public partial interface IServiceControllerClientController
        {
            /// <summary>
            /// Test API
            /// </summary>
            /// <param name="left"></param>
            /// <param name="right"></param>
            /// <returns></returns>
            AutoCSer.Net.ReturnCommand<int> Add(int left, int right);
        }
}namespace AutoCSer.Document.NativeAOT.Service
{
        /// <summary>
        /// An example of generate the API definition of the client controller interface 
///            生成客户端控制器接口 API 定义示例
        /// </summary>
        [AutoCSer.Net.CommandServer.ServerControllerInterface(typeof(IServiceControllerMethodEnum))]
        public partial interface IServiceController { }
        /// <summary>
        /// An example of generate the API definition of the client controller interface 
///            生成客户端控制器接口 API 定义示例 (The method sequence number maps the enumeration type)
        /// </summary>
        public enum IServiceControllerMethodEnum
        {
            /// <summary>
            /// [0] Test API
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Add = 0,
        }
}namespace AutoCSer.Document.CodeGenerator.MemoryDatabase
{
        /// <summary>
        /// An example of generate the API definition of the client node interface 
///            生成客户端节点接口 API 定义示例 client node interface
        /// </summary>
        [AutoCSer.CommandService.StreamPersistenceMemoryDatabase.ClientNode(typeof(AutoCSer.Document.CodeGenerator.MemoryDatabase.IServerNode))]
        public partial interface IServerNodeClientNode
        {
            /// <summary>
            /// Test API
            /// </summary>
            /// <param name="left"></param>
            /// <param name="right"></param>
            /// <returns></returns>
            AutoCSer.CommandService.StreamPersistenceMemoryDatabase.ResponseParameterAwaiter<int> Add(int left, int right);
        }
}namespace AutoCSer.Document.CodeGenerator.MemoryDatabase
{
        /// <summary>
        /// An example of generate the API definition of the local client node interface 
///            生成本地客户端节点接口 API 定义示例 local client node interface
        /// </summary>
        [AutoCSer.CommandService.StreamPersistenceMemoryDatabase.ClientNode(typeof(AutoCSer.Document.CodeGenerator.MemoryDatabase.ILocalNode))]
        public partial interface ILocalNodeLocalClientNode
        {
            /// <summary>
            /// Test API
            /// </summary>
            /// <param name="left"></param>
            /// <param name="right"></param>
            /// <returns></returns>
            AutoCSer.CommandService.StreamPersistenceMemoryDatabase.LocalServiceQueueNode<AutoCSer.CommandService.StreamPersistenceMemoryDatabase.LocalResult<int>> Add(int left, int right);
        }
}namespace AutoCSer.Document.CodeGenerator.MemoryDatabase
{
        /// <summary>
        /// An example of generate the API definition of the local client node interface 
///            生成本地客户端节点接口 API 定义示例
        /// </summary>
        [AutoCSer.CommandService.StreamPersistenceMemoryDatabase.ServerNodeType(typeof(ILocalNodeMethodEnum))]
        public partial interface ILocalNode { }
        /// <summary>
        /// An example of generate the API definition of the local client node interface 
///            生成本地客户端节点接口 API 定义示例 (Node method sequence number mapping enumeration type)
        /// </summary>
        public enum ILocalNodeMethodEnum
        {
            /// <summary>
            /// [0] Test API
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Add = 0,
        }
}namespace AutoCSer.Document.CodeGenerator.MemoryDatabase
{
        /// <summary>
        /// An example of generate the API definition of the client node interface 
///            生成客户端节点接口 API 定义示例
        /// </summary>
        [AutoCSer.CommandService.StreamPersistenceMemoryDatabase.ServerNodeType(typeof(IServerNodeMethodEnum))]
        public partial interface IServerNode { }
        /// <summary>
        /// An example of generate the API definition of the client node interface 
///            生成客户端节点接口 API 定义示例 (Node method sequence number mapping enumeration type)
        /// </summary>
        public enum IServerNodeMethodEnum
        {
            /// <summary>
            /// [0] Test API
            /// int left 
            /// int right 
            /// 返回值 int 
            /// </summary>
            Add = 0,
        }
}
#endif